"""Add analysis details

Revision ID: c3a1217e1acc
Revises: 76f5ac37298f
Create Date: 2026-09-20 14:18:58.253435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a1217e1acc'
down_revision: Union[str, Sequence[str], None] = '76f5ac37298f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('skills_detected', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('missing_sections', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'missing_sections')
    op.drop_column('analyses', 'skills_detected')
    op.drop_column('analyses', 'summary')
    # ### end Alembic commands ###
